WIP: Modular community loading
Tribler/gumby pull request #301
Opened 2017-02-25 13:16 UTC by qstokkink

This resolves #300 and #298. Depends on https://github.com/Tribler/tribler/pull/2815 .

This allows experiment creators to easily isolate and/or overwrite default communities with their own through community launch profiles (CommunityLauncher objects).

2017-03-03 10:04 UTC, qstokkink commented
@devos50 Can you allow testing on this?

2017-03-03 15:36 UTC, devos50 commented
ok to test

2017-03-03 15:49 UTC, qstokkink commented
@devos50 do you have time to review this?

2017-03-03 15:50 UTC, devos50 commented
@qstokkink yeah, I will review it in a moment. Have you tested it already?

2017-03-03 15:52 UTC, devos50 commented
Also, it's very nice that you have written a small guide. Can you please include this somewhere in our Gumby documentation and make a link to this in the README.md? This will benefit many students who want to run their experiments.

2017-03-03 17:04 UTC, qstokkink commented
@devos50 I could not get this to crash in my (small) tests.

Also 2 questions:

1. Where should the new documentation be located (there is no doc folder)?
2. How is Gumby currently being tested?

2017-03-03 17:09 UTC, devos50 commented
@qstokkink I see. Please create a `docs` directory yourself in the root of the Gumby project. We should setup a nice readthedocs page for Gumby where we organise all documentation. Please use the `rst` format to create your documentation so it integrates seamlessly in readthedocs.

We are currently running the experiment as specified in `local_processguard.conf` on each PR on Gumby. This only runs a simple command that generates some I/O and graphs the process guard statistics. It would be nice if we have an additional, more sophisticated test that uses Tribler and/or Dispersy but whether you want to create it for this PR, is up to you.

2017-03-03 17:30 UTC, qstokkink commented
@devos50 Thanks, I'll put it in a `docs` folder: in the mean time I will mark this as WIP.

Furthermore, my suggestion would be to add some unit tests for Gumby once #295 has been resolved and we have a stable base. Do you agree?

2017-03-03 17:39 UTC, devos50 commented
That's fine!

2017-03-04 07:33 UTC, qstokkink commented
Alright, I slept on this. There are two functionalities I really want/need to have unit tested, regardless of whether they need to be refactored later. I'll include these in the `tests` folder (consistent with Dispersy).

2017-03-04 12:30 UTC, qstokkink commented
@devos50 Alright, this has (what I consider to be minimal) unit tests and documentation: ready for review.

2017-03-06 07:41 UTC, devos50 requested changes

2017-03-06 07:41 UTC, devos50 commented on gumby/experiments/community_launcher.py
> +        Should not launch this before some other launcher has completed
Please end sentences with a dot.

2017-03-06 07:41 UTC, devos50 commented on gumby/experiments/community_launcher.py
> +class BarterCommunityLauncher(CommunityLauncher):
I think you can leave this one out since it's unused at the moment.

2017-03-06 07:41 UTC, devos50 commented on gumby/experiments/gumby_session.py
> +    Object in charge of loading communities into dispersy.
Dispersy (with capital D)

2017-03-06 07:41 UTC, devos50 commented on gumby/experiments/isolated_community_loader.py
> +        Wrap a child launcher, given a unique sesion id
*session

2017-03-06 07:41 UTC, devos50 commented on gumby/experiments/isolated_community_loader.py
> +class IsolatedLauncherWrapper(CommunityLauncher):
I don't really feel like it's necessary to create a whole subclass, just to change the master member when launching a community. Can you somehow combine this class with its superclass (`CommunityLauncher`)? Or do you have a good reason to do it like this?

2017-03-06 09:39 UTC, qstokkink commented on gumby/experiments/community_launcher.py
> +class BarterCommunityLauncher(CommunityLauncher):
If I leave this out, the DefaultCommunityLoader would be inconsistent with Tribler's defaultly loaded communities. This is core functionality of the DefaultCommunityLoader.

2017-03-06 09:45 UTC, qstokkink commented on gumby/experiments/isolated_community_loader.py
> +class IsolatedLauncherWrapper(CommunityLauncher):
Yes, I could combine it. However, this is a non-trivial extension of default CommunityLauncher behavior. Furthermore, this separates user launcher implementations from the test suite, which is desireable functionality in a test suite.

2017-03-06 13:12 UTC, qstokkink commented
@devos50 Fixed and rebased!

2017-03-07 09:15 UTC, devos50 requested changes
I've reviewed the documentation. After you've fixed/addressed my comments, don't forget to fix the commit history.

2017-03-07 09:15 UTC, devos50 commented on gumby/experiments/community_launcher.py
> +        :type community: Tribler.dispersy.community.Community or None
Please make sure to move these changes to the previous commit (or squash them)

2017-03-07 09:15 UTC, devos50 commented on gumby/tests/__init__.py
> +This folder contains unit tests for the Gumby testing framework
Please end sentences with a dot.

2017-03-07 09:15 UTC, devos50 commented on docs/community_isolation.rst
> +This document assumes the reader has a basic understanding of running Gumby experiments, creating Dispersy communities and running them through the `TriblerExperimentScriptClient` class.
`` does not work in RST.

2017-03-07 09:15 UTC, devos50 commented on docs/community_isolation.rst
> +This document assumes the reader has a basic understanding of running Gumby experiments, creating Dispersy communities and running them through the `TriblerExperimentScriptClient` class.
Please add the purpose of the guide in the first sentence.

2017-03-07 09:15 UTC, devos50 commented on docs/community_isolation.rst
> +Isolating and replacing communities
I would explicitly say 'Dispersy communities'

2017-03-07 09:15 UTC, devos50 commented on docs/community_isolation.rst
> +As you may have noticed, the communities loaded by the `TriblerExperimentScriptClient` are the wild communities as loaded by Tribler (which you can toggle by setting the correct flags in the `Session
wild -> live

2017-03-07 09:27 UTC, qstokkink commented
@devos50 Do you want the commit history changed? (If so: in what way?)

2017-03-07 09:28 UTC, devos50 commented
@qstokkink something like 3 commits:
-added community launcher/loader
-written unit tests
-written docs

2017-03-07 09:34 UTC, qstokkink commented on docs/community_isolation.rst
> +This document assumes the reader has a basic understanding of running Gumby experiments, creating Dispersy communities and running them through the `TriblerExperimentScriptClient` class.
http://stackoverflow.com/a/12365251 ` :code:`` ` should work, how was this handled in the rest of the docs?

2017-03-07 09:55 UTC, qstokkink commented
@devos50 Done and done 👍

2017-03-13 15:33 UTC, egbertbouman requested changes
Other than that one small remark, it looks great!

2017-03-13 15:33 UTC, egbertbouman commented on gumby/experiments/community_launcher.py
> +        return "HiddenTunnelCommunityMultichain"
This one got removed (see https://github.com/Tribler/tribler/pull/2852)

2017-03-13 17:15 UTC, qstokkink commented
@devos50 @egbertbouman all fixed!

2017-03-13 17:22 UTC, devos50 approved these changes

2017-03-13 17:22 UTC, devos50 commented
Thanks!

2017-03-13 17:23 UTC, merged