READY: Added Gumby hello world tutorial
Tribler/gumby pull request #336
Opened 2017-06-20 13:12 UTC by qstokkink

This PR adds a hello-world tutorial for basic Gumby usage.

2017-06-20 13:15 UTC, qstokkink commented
@devos50 Ready for review!

2017-06-21 08:30 UTC, devos50 requested changes

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +This document assumes the reader has a basic understanding of creating Dispersy communities.
Maybe add a reference to the dispersy documentation here? dispersy.readthedocs.org

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +Configuration files mainly fall into one of two categories:
"Into one of the two *following* categories"

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +    # At 0 seconds, make sure our HelloWorldCommunity does not communicate with the outside world
I would say: At 0 seconds into the experiment ... (also for the subsequent comments)

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +It is common to use the ``_module`` postfix when naming your module python file.
I would add: "An example of a Python module file is given below".

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +    class HelloWorldCommunityLoader(IsolatedCommunityLoader):
Please reference the document explaining the loader/launcher.

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +Furthermore, why one isolates Dispersy Communities and how the Communities are made will also remain outside of the scope of this document.
Please don't capitalize `Communities`

2017-06-21 08:30 UTC, devos50 commented on docs/hello_world.rst
> +You are now ready to run your experiment! You can do so by making the following call (make sure you followed the README setup instructions correctly):
"By running the following command"

2017-06-21 11:16 UTC, qstokkink commented
@devos50 Fixed 👍

2017-06-22 09:16 UTC, devos50 approved these changes

2017-06-22 09:16 UTC, merged