Add scalability experiment for IPv8 and Trustchain
Tribler/gumby pull request #404
Opened 2019-02-25 14:04 UTC by grimadas

Simple experiment with some number of nodes are sending transactions to one peer(aka leader peer). 
Leader peer tracks Trustchain blocks and their arrival time using listener. 
The arrival time is after used to build an estimated peer throughput histogram.

2019-02-25 14:05 UTC, qstokkink commented
ok to test

2019-02-26 14:58 UTC, devos50 requested changes

2019-02-26 14:58 UTC, devos50 commented on experiments/trustchain/trustchain_module.py
> +        transaction = {"up": up, "down": down, "from_peer": self.my_id, "to_peer": str(peer)}
You are adding the string representation of a `Peer` object to the transaction. Please only include the (numeric) id of the peer.

2019-02-26 14:58 UTC, devos50 commented on experiments/trustchain/trustchain_module.py
> +            Send block_num of blocks per second to leader peer per second.
We usually indent these comments one tab to the left.

2019-03-08 15:39 UTC, grimadas commented
I have problems running it on jenkins, no idea why.
https://jenkins-ci.tribler.org/job/pers/job/validation_experiment_trustchain_bulat/54/

2019-03-08 21:04 UTC, grimadas commented
All issues fixed,  see [last build](https://jenkins-ci.tribler.org/job/pers/job/validation_experiment_trustchain_bulat/63/) on jenkins

2019-03-11 09:50 UTC, devos50 requested changes

2019-03-11 09:50 UTC, devos50 commented on experiments/trustchain/trustchain_module.py
> +        t_file = open(self.file_name, "a")
You can use `with open(...)` to avoid explicitly adding the `close` statement.

2019-03-11 09:50 UTC, devos50 commented on experiments/trustchain/trustchain_module.py
> +        t_file = open(self.block_stat_file, "w")
See my comment above 👍

2019-03-11 10:07 UTC, devos50 approved these changes

2019-03-11 10:07 UTC, merged