READY: Added the possibility of using for loops within scenario files.
Tribler/gumby pull request #407
Opened 2019-03-03 13:15 UTC by DanGraur

It is now possible to use for loops inside scenario files. For loops can also make use of their control variable to either set parameters in the function call or to select which nodes will execute the for loop itself. This PR also adds a few scenarios specifically for exemplifying and testing the behavior of the for loops.

For loops we have the following syntax:
```
@hh:mm:ss for <control_variable> in <left_bound> to <right_bound> call <callable> [<unnamed_params>] [<named_params>] [<peerspec>]
```
The `<left_bound>` and `<right_bound>` are inclusive, and need not be `<left_bound> <= <right_bound>`, i.e. it can also be `<right_bound> >= <left_bound>`. The increments are currently either `+1` or `-1`, depending on the bounds.

It is possible to use the `<control_variable>` as a named or unnamed parameter. It should be noted, however, that if there exists a variable with the same name, the variable takes higher precedence as a parameter, and its value will be used. Should I change this behavior such that an error is thrown when we have conflicting names?

It is also possible to use the `<control_variable>`, or a scalar in the `peerspec` part of the `for` loop (not both at the same time). It is not possible to use exclusion semantics together with the `<control_variable>` yet, i.e. use `!` before `$<control_variable>` in the `peerspec` to denote that a node should not invoke the callable for this iteration.

2019-03-04 07:57 UTC, qstokkink requested changes
Nice 👍

Could you add some `# TODO:`'s to the regex and peer parse sections to show future programmers where to implement `peerspec` substitutions?

2019-03-04 08:52 UTC, devos50 reviewed
Nice addition!

I have a general comment. I noticed that you did add some new experiments to Gumby (which executes a scenario file with some for loops in it). I would prefer that these files are actively used in either an experiment on Jenkins (e.g. as part of the testers when making a PR) or within a unit test. I think that running this experiment as an experiment itself is a bit too much and it would be nice if you could create a unit test out of it. We already have a few unit tests that are executed when making a PR (see the `gumby/tests` directory).

What do you think about this?

2019-03-06 11:49 UTC, DanGraur commented
Sorry for the late response @qstokkink and @devos50. Will do on both these requests!

2019-03-27 16:02 UTC, DanGraur commented
I've finished adding a test class which is automatically run using Jenkins. The class is called `TestForLoop` and is located in the `tests` package. It features unit tests which should validate the correctness of the for loop implementation, as well as exemplify how it can be used. I've also added two `TODO`s which should detail how to further process a line in the scenario file, such that the code can be simplified, but actually implementing this might require some effort.

2019-03-28 07:36 UTC, qstokkink commented
> I've also left in the scenarios which demonstrate how to use the for loops, as well as the class ForLoopTestModule. Should I remove them, or can they stay in?

Please keep them. Our documentation is already pretty sparse. The more documentation we have, the better.

Maybe it's best to move them into a single `.rst` (maybe `forloops.rst`?) file in the `/doc` folder though, otherwise they might get thrown out.

2019-04-01 18:48 UTC, DanGraur commented
Ok, I've added the `.rst` file in the `/doc` folder. If it's ok, I called it `advanced_scenario_concepts.rst` (even though they might not be that advanced) since it also documents variables, not just `for` loops. I should mention that I also left the scenarios which exemplify the `for` loop and its limitations (these two scenarios are in `experiments/test_scenarios/for_loop`), and also a helper class (also located in `experiments/test_scenarios/for_loop`) whose methods are used as `experiment_callback`s  in these aforementioned scenarios. Should I leave those in, or should I remove them, now that there is some documentation for these new features?

2019-04-03 14:21 UTC, qstokkink approved these changes
Nice.

@devos50 any comments on this?

2019-04-05 07:14 UTC, devos50 approved these changes

2019-04-05 07:14 UTC, devos50 commented
Nice contribution!

2019-04-05 07:15 UTC, merged